
// Common icon names used in our application
export type IconName = 
  | 'LayoutDashboard'
  | 'Users'
  | 'Settings'
  | 'BookOpen'
  | 'Flag'
  | 'CheckSquare'
  | 'BarChart'
  | 'LogIn'
  | 'UserPlus'
  | 'Compass'
  | 'Home'
  | 'Bell'
  | 'MessageSquare'
  | 'Calendar'
  | 'School'
  | 'BookMarked'
  | 'User'
  | 'Award'
  | 'Certificate'
  | 'Medal'
  | 'CreditCard'
  | 'Heart'
  | 'Star'
  | 'Lightbulb'
  | 'HelpCircle'
  | 'LogOut';
