
export const featuredCourses = [
  {
    id: 1,
    title: "Desarrollo Web Completo con HTML5, CSS3, JS y React",
    description: "Aprende desarrollo web desde cero. Este curso abarca todo lo necesario para convertirte en un desarrollador web frontend completo, incluyendo HTML5, CSS3, JavaScript moderno y React.",
    instructor: "María González",
    price: 49.99,
    rating: 4.8,
    students: 15420,
    hours: 42,
    level: "principiante",
    category: "Desarrollo Web",
    image: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=2062&auto=format&fit=crop",
    featured_instructor: "María González",
    currency: "eur",
    duration_text: "42 horas",
    is_published: true,
    created_at: "2023-06-15T10:00:00Z",
    updated_at: "2023-09-20T14:30:00Z"
  },
  {
    id: 2,
    title: "Programación Avanzada en Python para Ciencia de Datos",
    description: "Domina Python y las bibliotecas más importantes como NumPy, Pandas, Matplotlib y scikit-learn. Aprende a implementar algoritmos de machine learning y análisis de datos con casos prácticos.",
    instructor: "Carlos Rodríguez",
    price: 59.99,
    rating: 4.7,
    students: 8932,
    hours: 36,
    level: "intermedio",
    category: "Ciencia de Datos",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
    featured_instructor: "Carlos Rodríguez",
    currency: "eur",
    duration_text: "36 horas",
    is_published: true,
    created_at: "2023-07-22T09:15:00Z",
    updated_at: "2023-10-05T11:20:00Z"
  },
  {
    id: 3,
    title: "Marketing Digital: Estrategias Completas para 2023",
    description: "Aprende a crear estrategias efectivas de marketing digital. El curso cubre SEO, SEM, marketing de contenidos, redes sociales, email marketing, analytics y mucho más.",
    instructor: "Laura Martínez",
    price: 49.99,
    rating: 4.6,
    students: 12845,
    hours: 28,
    level: "principiante",
    category: "Marketing",
    image: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?q=80&w=2074&auto=format&fit=crop",
    featured_instructor: "Laura Martínez",
    currency: "eur",
    duration_text: "28 horas",
    is_published: true,
    created_at: "2023-05-10T16:45:00Z",
    updated_at: "2023-09-12T08:50:00Z"
  },
  {
    id: 4,
    title: "Diseño UX/UI: De principiante a profesional",
    description: "Aprende a diseñar interfaces de usuario atractivas y funcionales. Domina herramientas como Figma y Adobe XD, y aprende los principios de usabilidad, investigación de usuarios y prototipado.",
    instructor: "Daniel López",
    price: 54.99,
    rating: 4.9,
    students: 7562,
    hours: 32,
    level: "principiante",
    category: "Diseño",
    image: "https://images.unsplash.com/photo-1587440871875-191322ee64b0?q=80&w=2071&auto=format&fit=crop",
    featured_instructor: "Daniel López",
    currency: "eur",
    duration_text: "32 horas",
    is_published: true,
    created_at: "2023-08-05T10:30:00Z",
    updated_at: "2023-10-15T09:20:00Z"
  },
  {
    id: 5,
    title: "Inteligencia Artificial y Machine Learning en la Práctica",
    description: "Comprende los fundamentos de la IA y el machine learning, y aprende a implementar soluciones prácticas. El curso incluye algoritmos de clasificación, regresión, clustering y redes neuronales.",
    instructor: "Javier García",
    price: 69.99,
    rating: 4.8,
    students: 5231,
    hours: 40,
    level: "avanzado",
    category: "Inteligencia Artificial",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=2065&auto=format&fit=crop",
    featured_instructor: "Javier García",
    currency: "eur",
    duration_text: "40 horas",
    is_published: true,
    created_at: "2023-04-18T14:20:00Z",
    updated_at: "2023-08-22T16:10:00Z"
  },
  {
    id: 6,
    title: "Desarrollo de Aplicaciones Móviles con React Native",
    description: "Aprende a crear aplicaciones móviles multiplataforma con React Native. El curso cubre componentes, navegación, gestión de estado, APIs nativas y publicación en App Store y Google Play.",
    instructor: "Ana Sánchez",
    price: 59.99,
    rating: 4.7,
    students: 6789,
    hours: 38,
    level: "intermedio",
    category: "Desarrollo Móvil",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=2070&auto=format&fit=crop",
    featured_instructor: "Ana Sánchez",
    currency: "eur",
    duration_text: "38 horas",
    is_published: true,
    created_at: "2023-03-30T11:15:00Z",
    updated_at: "2023-07-25T13:40:00Z"
  },
  {
    id: 7,
    title: "Big Data y Analítica de Datos con Hadoop y Spark",
    description: "Domina las tecnologías clave para el procesamiento y análisis de grandes volúmenes de datos. Aprende a utilizar Hadoop, Spark, Hive y técnicas de visualización de datos.",
    instructor: "Miguel Fernández",
    price: 64.99,
    rating: 4.6,
    students: 4328,
    hours: 35,
    level: "avanzado",
    category: "Big Data",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop",
    featured_instructor: "Miguel Fernández",
    currency: "eur",
    duration_text: "35 horas",
    is_published: true,
    created_at: "2023-05-25T13:20:00Z",
    updated_at: "2023-09-05T15:10:00Z"
  },
  {
    id: 8,
    title: "Desarrollo Backend con Node.js, Express y MongoDB",
    description: "Aprende a construir APIs robustas y escalables con Node.js. El curso cubre Express, MongoDB, autenticación, autorización, y despliegue de aplicaciones backend.",
    instructor: "Roberto Hernández",
    price: 49.99,
    rating: 4.9,
    students: 7123,
    hours: 30,
    level: "intermedio",
    category: "Desarrollo Backend",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop",
    featured_instructor: "Roberto Hernández",
    currency: "eur",
    duration_text: "30 horas",
    is_published: true,
    created_at: "2023-06-10T09:45:00Z",
    updated_at: "2023-10-02T10:15:00Z"
  },
  {
    id: 9,
    title: "DevOps y CI/CD: Automatización y Entrega Continua",
    description: "Domina las herramientas y prácticas de DevOps moderno. Aprende sobre Docker, Kubernetes, CI/CD, monitorización, y automatización de infraestructura como código.",
    instructor: "Elena Torres",
    price: 69.99,
    rating: 4.8,
    students: 3965,
    hours: 34,
    level: "avanzado",
    category: "DevOps",
    image: "https://images.unsplash.com/photo-1607743386760-88f10eb6a580?q=80&w=2070&auto=format&fit=crop",
    featured_instructor: "Elena Torres",
    currency: "eur",
    duration_text: "34 horas",
    is_published: true,
    created_at: "2023-07-15T15:30:00Z",
    updated_at: "2023-10-10T14:20:00Z"
  },
  {
    id: 10,
    title: "Desarrollo de Videojuegos con Unity y C#",
    description: "Aprende a crear videojuegos profesionales desde cero con Unity. El curso cubre programación en C#, diseño de niveles, física, IA, animaciones y publicación multiplataforma.",
    instructor: "Pablo Moreno",
    price: 59.99,
    rating: 4.7,
    students: 8452,
    hours: 45,
    level: "principiante",
    category: "Desarrollo de Videojuegos",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=2071&auto=format&fit=crop",
    featured_instructor: "Pablo Moreno",
    currency: "eur",
    duration_text: "45 horas",
    is_published: true,
    created_at: "2023-05-05T12:10:00Z",
    updated_at: "2023-08-15T11:30:00Z"
  },
  {
    id: 11,
    title: "Ciberseguridad: Protección y Hacking Ético",
    description: "Aprende a proteger sistemas y redes contra amenazas cibernéticas. El curso cubre principios de seguridad, análisis de vulnerabilidades, pentesting, ingeniería social y gestión de incidentes.",
    instructor: "Sofía Vargas",
    price: 64.99,
    rating: 4.8,
    students: 6234,
    hours: 38,
    level: "intermedio",
    category: "Ciberseguridad",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=2070&auto=format&fit=crop",
    featured_instructor: "Sofía Vargas",
    currency: "eur",
    duration_text: "38 horas",
    is_published: true,
    created_at: "2023-04-10T14:25:00Z",
    updated_at: "2023-09-18T13:15:00Z"
  },
  {
    id: 12,
    title: "Blockchain y Desarrollo de Smart Contracts",
    description: "Comprende la tecnología blockchain y aprende a desarrollar contratos inteligentes. El curso cubre Ethereum, Solidity, tokens, DApps y casos de uso empresariales.",
    instructor: "Luis Ramírez",
    price: 69.99,
    rating: 4.6,
    students: 3567,
    hours: 32,
    level: "avanzado",
    category: "Blockchain",
    image: "https://images.unsplash.com/photo-1639762681057-408e52192e55?q=80&w=2033&auto=format&fit=crop",
    featured_instructor: "Luis Ramírez",
    currency: "eur",
    duration_text: "32 horas",
    is_published: true,
    created_at: "2023-06-20T10:50:00Z",
    updated_at: "2023-10-08T09:40:00Z"
  }
];

// Add the missing courseCategories export
export const courseCategories = [
  "Todos",
  "Desarrollo Web",
  "Ciencia de Datos",
  "Marketing",
  "Diseño",
  "Inteligencia Artificial",
  "Desarrollo Móvil",
  "Big Data",
  "Desarrollo Backend",
  "DevOps",
  "Desarrollo de Videojuegos",
  "Ciberseguridad",
  "Blockchain"
];
